funcion uno: have a problem: need to go out
Fatal error: Call to undefined function insertProduct() in
C:\wamp\www\Hologramia\functions\function_tests.php on line 19